{% set name = "roms-tools" %}
{% set version = "2.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roms_tools-{{ version }}.tar.gz
  sha256: 0b73cc7d6150c23ec160be57e6b89a5b8f4e04a94e50dbbc1bb891a4001b2c59	

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - setuptools-scm >=7.0
    - check-manifest
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2022.6.0
    - numpy
    - pooch
    - matplotlib-base
    - cartopy
    - packaging
    - scipy
    - gcm_filters
    - netcdf4
    - pyyaml
    - pyamg
    - bottleneck
    - dask
    - regionmask

test:
  requires:
    - python {{ python_min }}
  imports:
    - roms_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CWorthy-ocean/roms-tools
  summary: Tools for creating input files for UCLA-ROMS simulations
  license: Apache-2.0
  license_file: LICENSE
  description: |
    **ROMS-Tools** is a Python package designed for creating the input files necessary to run a ROMS simulation. The package 
    simplifies the process of generating grid, tidal forcing, surface forcing, initial conditions, and boundary forcing.
    ROMS-Tools supports the generation of biogeochemical forcing consistent with ROMS-MARBL.

extra:
  recipe-maintainers:
    - NoraLoose
