{% set name = "roms-tools" %}
{% set version = "3.1.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roms_tools-{{ version }}.tar.gz
  sha256: 1ca13644a7ffee7337a57b9d4aeb14bc4a5af85803329d8531181e35492c1e3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - setuptools-scm >=7.0
    - check-manifest
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2022.6.0,<2025.8.0
    - numpy >2.0,<2.3
    - pooch
    - matplotlib-base
    - cartopy
    - packaging
    - scipy
    - gcm_filters >=0.5.1
    - netcdf4
    - pyyaml
    - pyamg
    - bottleneck
    - regionmask
    - xgcm >=0.9.0
    - numba >=0.61.2
    - pydantic >2,<3
    - dask
    - xesmf >=0.8.8
    - gcsfs
    - copernicusmarine
    - zarr

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - roms_tools
  commands:
    - pip check

about:
  home: https://github.com/CWorthy-ocean/roms-tools
  summary: Tools for creating input files for UCLA-ROMS simulations
  license: Apache-2.0
  license_file: LICENSE
  description: |
    **ROMS-Tools** is a Python package designed for creating the input files necessary to run a UCLA-ROMS simulation, with or without MARBL biogeochemistry. 
    The package simplifies the process of generating grid, tidal forcing, surface forcing, initial conditions, boundary forcing, river forcing, carbon dioxide removal (CDR) forcing, and nesting.
    In addition to input generation, ROMS-Tools includes utilities for postprocessing and analysis, particularly for CDR monitoring, reporting, and verification (MRV).

extra:
  recipe-maintainers:
    - NoraLoose
